---
- name: Deploy a Pod in Kubernetes
  hosts: localhost
  tasks:
    - name: Create a Kubernetes Pod
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx-pod
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
